server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 关键：允许请求头中包含下划线
    underscores_in_headers on;


    location / {
        try_files $uri $uri/ /index.html;
    }


    location /bs/ {
        proxy_pass http://bs:8080;  # <-- 注意：这里加上了结尾斜杠 /

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location ~* ^/bs/.*\.(gif|jpg|jpeg|png|bmp|ico)$ {
            # 让 root 指向你挂载本地头像的容器内目录
            root /usr/share/nginx/html;
            # 把 /bs/ 抹去，变成纯文件名去 bstouxiang 文件夹里找
            rewrite ^/bs/(.*)$ /bstouxiang/$1 break;
            try_files $uri =404;
        }
}